apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-nginx
  name: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-nginx
    spec:
      containers:
      - image: 975050215788.dkr.ecr.ap-northeast-2.amazonaws.com/eks-demo-repo:682
        name: ipnginx
        ports: 
        - containerPort: 80
        resources: {}
status: {}

